import = ["~/.config/alacritty/nixos.toml", "~/.config/alacritty/macos.toml", "~/.config/alacritty/theme.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "RecursiveMnLnrStBlk Nerd Font"
style = "Regular"

[font.bold_italic]
family = "RecursiveMnLnrStBlk Nerd Font"
style = "Italic"

[font.normal]
family = "RecursiveMnLnrSt Nerd Font"

[font.offset]
y = 2

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 100000
multiplier = 1

[window]
decorations = "None"
startup_mode = "Maximized"
