[font]
size = 10

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
key = "T"
mods = "Alt"

[keyboard.bindings.command]
args = ["new-window", "-c", "~"]
program = "tmux"

[[keyboard.bindings]]
key = "W"
mods = "Alt"

[keyboard.bindings.command]
args = ["kill-pane"]
program = "tmux"

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["select-window", "-t", "-1"]
program = "tmux"

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["select-window", "-t", "+1"]
program = "tmux"

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt|Super"

[keyboard.bindings.command]
args = ["swap-window", "-t", "-1", ";", "select-window", "-t", "-1"]
program = "tmux"

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt|Super"

[keyboard.bindings.command]
args = ["swap-window", "-t", "+1", ";", "select-window", "-t", "+1"]
program = "tmux"

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "1"]
program = "tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "2"]
program = "tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "3"]
program = "tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "4"]
program = "tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "5"]
program = "tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "6"]
program = "tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "7"]
program = "tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "8"]
program = "tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "9"]
program = "tmux"
