#!/bin/bash

p=~/bar2

[ -e "$p" ] && rm "$p"
mkfifo "$p"

# xtitle -sf 'X%s' > "$p" &

. ~/Utils/panel_colors

cat "$p" | ~/Utils/bar2_reader | lemonbar -g "x24" -f "Fira Mono-9" -f "Fira Mono-9:style=Bold" -f "fontello-12" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -b &

wait
