#!/bin/bash

p=~/bar2

[ -e "$p" ] && rm "$p"
mkfifo "$p"

xtitle -sf 'X%{F#FF6699CC}%{B#FF515151}  %{B-}%{F-} %s' > "$p" &

. ~/Utils/panel_colors

cat "$p" | ~/Utils/bar2_reader | bar -g "x$PANEL_HEIGHT" -f "$PANEL_FONT_FAMILY-$PANEL_FONT_SIZE,FontAwesome-12,icomoon-12" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -b &

wait
