#!/bin/bash

while read -r line ; do
    case $line in
        X*)
            output=${line#?}
            ;;
    esac

    printf "%s\n" "%{l}%{B#FF515151}%{F#FF6699CC} $(echo -e '\ue600') %{F-}%{B-} ${output}%{r}%{F#FFA09F93}$(echo -e '\uf142')%{F-} "
done
