#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

while true; do
    echo "S" > "$PANEL_FIFO"
    sleep 0.25
done &

. ~/Utils/panel_colors

cat "$PANEL_FIFO" | ~/Utils/panel_bar | lemonbar -g "x24" -f "Panic Sans-9" -f "Panic Sans-9:style=Bold" -f "fontello-12" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
