#! /bin/bash

. ~/Utils/colors.sh

. panel_colors

num_mon=$(bspc query -M | wc -l)

function get-panel-right() {
    python ~/Utils/panel.py
}

while read -r line ; do
    case $line in
        S*)
            panel_right="$(get-panel-right)"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        # TODO: Underline color based on selected desktop.
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FG}%{B$COLOR_FOCUSED_BG}%{U$COLOR_UNDERLINE}%{+u} X %{-u}%{B-}%{F-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FG}%{B$COLOR_FOCUSED_BG}%{U$COLOR_UNDERLINE}%{+u} X %{-u}%{B-}%{F-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FG}%{B$COLOR_FOCUSED_BG}%{U$COLOR_UNDERLINE}%{+u} X %{-u}%{B-}%{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${panel_right}"
done
