#! /bin/sh

bspc config border_width 2
bspc config window_gap 24

bspc config split_ratio 0.618 # Golden ratio.
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d "1" "2" "3" "4" "5" "6" "7" "8" "9" "0"

bspc rule -a Gimp follow=on floating=on
bspc rule -a Firefox desktop=^2 focus=on

feh --bg-center ~/Pictures/wallpaper &
panel &
