cd ~/.vim/bundle/
git clone https://github.com/mileszs/ack.vim ack
git clone https://github.com/kchmck/vim-coffee-script coffeescript
git clone https://github.com/tpope/vim-commentary commentary
git clone https://github.com/kien/ctrlp.vim ctrlp
git clone https://github.com/tpope/vim-fugitive fugitive
git clone https://github.com/airblade/vim-gitgutter gitgutter
git clone https://github.com/sjl/gundo.vim gundo
git clone https://github.com/othree/html5.vim html5
git clone https://github.com/suan/vim-instant-markdown instant-markdown
git clone https://github.com/tpope/vim-markdown markdown
git clone https://github.com/gregsexton/MatchTag matchtag
git clone https://github.com/scrooloose/nerdtree nerdtree
git clone https://github.com/Lokaltog/vim-powerline powerline
git clone https://github.com/tpope/vim-repeat repeat
git clone https://github.com/tpope/vim-sensible sensible
git clone https://github.com/mhinz/vim-startify startify
git clone https://github.com/mislav/stylish.vim stylish
git clone https://github.com/ervandew/supertab supertab
git clone https://github.com/tpope/vim-surround surround
git clone https://github.com/scrooloose/syntastic syntastic
git clone https://github.com/majutsushi/tagbar tagbar
