#!/bin/zsh

password_files=( ~/.password-store/**/*.gpg )
password_files=( "${password_files[@]##*/.password-store/}" )
password_files=( "${password_files[@]%.gpg}" )

loc=$(printf '%s\n' "${password_files[@]}" | dmenu-custom "$@")

pass -c "$loc"
rc=$?

if [[ "$loc" != "" ]] && [[ $rc -eq 0 ]]; then
    notify-send -u low "Password copied" "$loc"
fi;
