#!/bin/zsh

password_files=( ~/.password-store/**/*.gpg )
password_files=( "${password_files[@]##*/.password-store/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu-custom "$@")

pass -c "$password"

if [[ "$password" != "" ]]; then
    notify-send -u low 'Password copied' "$password"
fi;
