#! /bin/zsh

bspc config border_width 2
bspc config window_gap 24

bspc config split_ratio 0.382 # Golden ratio.
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

if [[ "$(hostname)" == $WORK_HOSTNAME ]]; then
    bspc monitor HDMI3 -n 1 -d 1 2 3 4 5
    bspc monitor HDMI2 -n 2 -d 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc rule -a Gimp follow=on floating=on
# bspc rule -a Firefox desktop=^2 focus=on

set_wallpaper.sh

~/Utils/panel &
