#!/bin/bash

source ~/Utils/colors.sh

bspc config border_width 3
bspc config window_gap 20
bspc config normal_border_color "$COLOR_01"
bspc config focused_border_color "$COLOR_04"
bspc config split_ratio 0.382 # Golden ratio.
# Remove borders for tiled windows in monocle mode.
bspc config borderless_monocle true
# Remove gaps for tiled windows in monocle mode.
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config top_padding "$PANEL_HEIGHT"
bspc config bottom_padding "$PANEL_HEIGHT"
# Focus the window under the pointer.
bspc config focus_follows_pointer true
# When focusing a monitor, put the pointer at its center.
bspc config pointer_follows_monitor true

if [[ "$(hostname)" == "$WORK_HOSTNAME" ]]; then
    bspc monitor HDMI3 -n 1 -d 1 2 3 4 5
    bspc monitor HDMI2 -n 2 -d 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc rule -a Gimp follow=on floating=on
# bspc rule -a Firefox desktop=^2 focus=on

set_wallpaper.sh

~/Utils/panel &
~/Utils/bar2 &
compton --config ~/.compton.conf &
trayer --height 16 --transparent true --alpha 0 --tint 0x393939 --widthtype request --align right &
