#!/bin/bash

source ~/Utils/colors.sh

bspc config border_width 3
bspc config window_gap 0
bspc config top_padding 34
bspc config bottom_padding 34
bspc config left_padding 10
bspc config right_padding 10
bspc config split_ratio 0.42

bspc config normal_border_color "$COLOR_00"
bspc config focused_border_color "$COLOR_05"
bspc config presel_border_color "$COLOR_08"

# Remove borders for tiled windows in monocle mode.
bspc config borderless_monocle true
# Remove gaps in monocle mode.
bspc config gapless_monocle true
# Go monocle if there’s only one tiled window in the desktop.
bspc config leaf_monocle true

bspc config focus_by_distance true
# Focus the window under the pointer.
bspc config focus_follows_pointer true
# When focusing a monitor, put the pointer at its center.
bspc config pointer_follows_monitor true

if [[ "$(hostname)" == "$WORK_HOSTNAME" ]]; then
    bspc monitor HDMI3 -n 1 -d 1 2 3 4 5 6 7
    bspc monitor HDMI2 -n 2 -d 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc rule -a Gimp follow=on floating=on
# bspc rule -a Firefox desktop=^2 focus=on

restart_wm.sh &
